services:
  - type: web
    name: online-shop
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:5000 app:app"
    envVars:
      - key: PORT
        value: 5000
